### PR TITLE
Phpunit8

### PR DESCRIPTION
**Pull request by greg0ire**
This adds compatibility with phpunit 8, and will require some changes to dev-kit (for instance merging https://github.com/sonata-project/dev-kit/pull/495). It is a proof that it is worth merging.

### CODE REVIEW

**Comment by kunicmarko20** [comment]
AFAIK phpunit8 doesn't work with symfony, was that fixed? since we use symfony bridge

**Comment by greg0ire** [comment]
It runs just fine locally, so I guess the answer is yes :)

**Comment by greg0ire** [comment]
Guess we also need https://github.com/sonata-project/dev-kit/pull/494/files to see the result…

**Comment by greg0ire** [comment]
Why isn't this working? :sweat_smile:

**Comment by greg0ire** [comment]
Maybe that info about 1.x needs to land on master? Let's create a manual merge PR…

**Comment by kunicmarko20** [comment]
is travis enabled for the new repo?

**Comment by greg0ire** [comment]
It builds 1.x and master, and I can see build requests here, but only for master PRs + master branch and 1.x branch. I also see in the settings that the webhook is triggered for this PR, to which Travis responds with 204 no content. I'm confused…

**Pull request closed without merging**
