### PR TITLE
Remove deleted elements before submit to avoid triggering validation

### LINKED ISSUE #4348: Sonata type collection delete row triggers constraints validation
I have a problem with sonata admin, specifically in a type collection field. Here's the scenario:

I have an entity called "Group" with a one to many relationship to the entity "Member"

In sonata admin I set up the admin classes for the 2 entities.

In the "Group admin" i create a collection type with the Member entity this way

```php
->add('members', 'sonata_type_collection', [
    'by_reference'          => false,
    'label'                 => 'Members',
    'type_options'          => ['delete' => true],
    'btn_add'               => "Add Member",
    'required'              => false,
    'constraints'           => $validation['members'],
],
[
    'edit'              => 'inline',
    'inline'            => 'table'
])
```
The member entity has 4 fields, one of which is required.

```php
->add('firstName', TextType::class, [
    'label'         => 'First Name'
    'constraints'   => [
        new NotBlank(['message' => 'Please enter the name.']),
    ]
])
```
If I click the "Add Member" button in the edit view, it adds a new row as expected. At that point, if I change my mind and decide to delete the newly added record, without adding the name, on save it's returning a validation error telling me 'Please enter the name.' on the field.

Shouldn't the delete action have priority over validation?

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is a bug fix.

Closes https://github.com/sonata-project/SonataAdminBundle/issues/4348.

## Changelog

```markdown
### Fixed
- Do not trigger validation on deleted rows of CollectionType
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
I have tried on a project and now the validation is not triggered when the collection item is marked for deletion.

WDYT @VincentLanglet ?

**Comment by VincentLanglet** [comment]
> I have tried on a project and now the validation is not triggered when the collection item is marked for deletion.
> 
> WDYT @VincentLanglet ?

The bug was rely annoying, this is a great fix.
Do you think we have a way to add test here or in sonataAdmin ?

I don't have a project to reproduce the bug and use the fix.

I'm ok merging and releasing this

**Review by VincentLanglet — DISMISSED** [review]

**Comment by jordisala1991** [comment]
> > I have tried on a project and now the validation is not triggered when the collection item is marked for deletion.
> > WDYT @VincentLanglet ?
> 
> The bug was rely annoying, this is a great fix. Do you think we have a way to add test here or in sonataAdmin ?
> 
> I don't have a project to reproduce the bug and use the fix.
> 
> I'm ok merging and releasing this

It is really problematic to test this properly... form type is here, base templates are on the admin-bundle, BUT the form type widget is on the persistence bundles...

So I guess the only way to test this is on the DoctrineORM/MongoDB persistence bundles, I can try it once released.

**Review by VincentLanglet — DISMISSED** [review]

**Comment by jordisala1991** [comment]
Let me try one more way to delete those items. Wait a bit for the merge.

**Comment by jordisala1991** [comment]
No more changes needed, this is the cleaner solution I could found.

I also tried to make it work somehow like this: https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php

Where on preSubmit it only removed from the $form object, and on the submit it removed from the $data object, but it does not work on our use case. It complains about extra fields (data submitted contains more things that the $form is expecting, because we remove from $form first).

There should be more pieces on Symfony code dealing with that, but I think it is not worth investigating more.

Current behavior is buggy since it does not let you remove invalid items, and the fix improves that.

EDIT: I guess the resizer from Symfony is expecting that when you remove an item, the $data will not contain it, it does not rely on a checkbox for removal, but the full removal on the frontend prior submit, that's why it works this way.

**Comment by jordisala1991** [comment]
I think this is the most correct solution @VincentLanglet . on Pre Submit we should make sure to remove extra data (data marked for removal) and to remove the form fields for that data (avoid adding them back to the form).

Then onSubmit we don't have:
* Data submitted because we previously filter it
* Form associated fields because it was also removed

Validation will work for fields not removed, but will not be triggered for removed fields.

**Comment by jordisala1991** [comment]
I will try to prepare a test now for the doctrine orm admin bundle.

**Review by VincentLanglet — APPROVED** [review]

**Comment by jordisala1991** [comment]
Something like this: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1737

**Pull request merged**
