### PR TITLE
fix: relative asset paths

### LINKED ISSUE #480: Relative Asset Paths
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
Direct dependencies required in composer.json:
sonata-project/admin-bundle              4.29.3                  4.29.3                  The missing Symfony Admin Generator
sonata-project/classification-bundle     4.8.0                   4.8.0                   Symfony SonataClassificationBundle
sonata-project/doctrine-extensions       2.3.0                   2.3.0                   Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 4.15.0                  4.15.0                  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  3.3.0                   3.3.0                   Lightweight Exporter library
sonata-project/intl-bundle               3.2.0                   3.2.0                   Symfony SonataIntlBundle
sonata-project/media-bundle              4.11.0                  4.11.0                  Symfony SonataMediaBundle
sonata-project/translation-bundle        dev-3.x-dev-kit e6ea40d dev-3.x-dev-kit e6ea40d SonataTranslationBundle

Transitive dependencies not required in composer.json:
sonata-project/block-bundle              5.1.0                   5.1.0                   Symfony SonataBlockBundle
sonata-project/form-extensions           2.3.0                   2.3.0                   Symfony form extensions
sonata-project/twig-extensions           2.4.0                   2.4.0                   Sonata twig extensions
```

</p>
</details>

## Subject

We're using symfony instances on our staging system in subdirectories. Unfortunately we ran into the problem, that the public assets of the sonataform bundle points to absolute paths. 

I think the paths need an relative "./" to be more flexible. See [entrypoints.json](https://github.com/sonata-project/form-extensions/blob/2.x/src/Bridge/Symfony/Resources/public/entrypoints.json) and [manifest.json](https://github.com/sonata-project/form-extensions/blob/2.x/src/Bridge/Symfony/Resources/public/manifest.json). 

I'm not so familiar with the webpack config, but I think changing the public path may deals with this fact, see [webpack.config.js](https://github.com/sonata-project/form-extensions/blob/2.x/webpack.config.js#L14).

### PR DESCRIPTION
**Pull request by konradmichalik**
## Subject

We're using symfony instances on our staging system in subdirectories. Unfortunately we ran into the problem, that the public assets of the sonataform bundle points to absolute paths. 

I think the paths need an relative "./" to be more flexible. See [entrypoints.json](https://github.com/sonata-project/form-extensions/blob/2.x/src/Bridge/Symfony/Resources/public/entrypoints.json) and [manifest.json](https://github.com/sonata-project/form-extensions/blob/2.x/src/Bridge/Symfony/Resources/public/manifest.json). 

I'm not so familiar with the webpack config, but I think changing the public path may deals with this fact, see [webpack.config.js](https://github.com/sonata-project/form-extensions/blob/2.x/webpack.config.js#L14).

Closes #480 .

## Changelog

```markdown
### Changed
- Added relative dot to public path within webpack config.
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Hi @jackd248 

when looking at the symfony documentation 
https://symfony.com/doc/current/frontend/encore/installation.html
the call is made with a `/`, see 
```
.setPublicPath('/build')
```
so our usage seem similar to what the documentation ask, no ?

@jordisala1991 are you familiar with such change ?

**Comment by Hanmac** [comment]
@VincentLanglet it depends on how the Web-Server is configured.

If the Project is the Web-Root or maybe the `public` folder.
Or in the case if you are a Developer, you might have the parent folder as root.

If webpack force to hard-code this, then it is bad design in my opinion.

**Comment by Hanmac** [comment]
@jackd248 

Your change doesn't work for me either

Before:
It tries to access `https://localhost.local/bundles/sonataform/379.js`
but it should try to access `https://localhost.local/<project>/public/bundles/sonataform/379.js`

Now it tries to access `https://localhost.local/<project>/public/<route>/bundles/sonataform/379.js`

**Comment by konradmichalik** [comment]
You're right, I wasn't able to fix this problem so far. 

Do you have an idea how to solve this kind of issue?

**Comment by Hanmac** [comment]
My current hotfix:

using your Branch, and then applied my own Redirect Controller

```php
class BundleFixController extends AbstractController
{
    #[Route('/admin/{something}/bundles/{path}', requirements: ['something' => '.+', 'path' => '.+'], methods: ['GET'])]
    public function bundleAction(RouterInterface $router, string $path): Response
    {
        $baseUrl = $router->getContext()->getBaseUrl();
        return $this->redirect($baseUrl . "/bundles/" . $path);
    }
}
```

This redirects `https://localhost.local/<project>/public/admin/<route>/bundles/<path>`
to `https://localhost.local/<project>/public/bundles/<path>`

For Future, I would like to see this webpack getting replaced with [AssetMapper](https://symfony.com/doc/current/frontend/asset_mapper.html) in the Future when Symfony 5.4 gets dropped

**Comment by VincentLanglet** [comment]
So does this PR solve something and should be merged or not ?

BTW, it need to be rebased.

**Comment by Hanmac** [comment]
> So does this PR solve something and should be merged or not ?
> 
> BTW, it need to be rebased.

No, right now it just shifts the problem from one wrong path (outside the project), to another (inside the project)
The only good thing, now that the wrong path is inside the project, you might capture it with a Redirect Controller

For the Base Path Problem, I found this:
https://stackoverflow.com/questions/51613055/encore-webpack-or-assets-generating-wrong-path-to-image-in-symfony-4

> WARNING   The value passed to setPublicPath() should *usually* start with "/" or be a full URL (http://...). If you're not sure, then you should probably change your public path and make this message disappear.. 

@VincentLanglet when is Sonata going to drop Symfony 5.4 Support?
The [AssetMapper](https://symfony.com/doc/current/frontend/asset_mapper.html) might look more interesting than webpack

**Comment by VincentLanglet** [comment]
> @VincentLanglet when is Sonata going to drop Symfony 5.4 Support? The [AssetMapper](https://symfony.com/doc/current/frontend/asset_mapper.html) might look more interesting than webpack

We're following https://symfony.com/releases#maintained-symfony-branches
so it will be end of the year.

But you can start a PR with AssetMapper if you want.

**Comment by Hanmac** [comment]
> > @VincentLanglet when is Sonata going to drop Symfony 5.4 Support? The [AssetMapper](https://symfony.com/doc/current/frontend/asset_mapper.html) might look more interesting than webpack
> 
> We're following https://symfony.com/releases#maintained-symfony-branches so it will be end of the year.
> 
> But you can start a PR with AssetMapper if you want.

I don't have exp on using asset mapper yet
especially on how to use it for a bundle like this instead of the main project

**Comment by konradmichalik** [comment]
Right, this PR is currently not the right solution. I close them for now.

**Comment by Hanmac** [comment]
> Hi @jackd248
> 
> when looking at the symfony documentation https://symfony.com/doc/current/frontend/encore/installation.html the call is made with a `/`, see
> 
> ```
> .setPublicPath('/build')
> ```
> 
> so our usage seem similar to what the documentation ask, no ?
> 
> @jordisala1991 are you familiar with such change ?

Comparing to this: 
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/public/manifest.json

the paths in the admin bundle uses relative paths, starting with `./`

So if this PR would use `./` too, would that fix the problem?
Or use better DatePicker?

**Pull request closed without merging**
