### PR TITLE
Fix datetimepicker with jQuery 3.6

### LINKED ISSUE #7830: jQuery 3.6 broke datetimepicker
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              4.12.0 4.12.0 The missing Symfony Admin Generator
sonata-project/block-bundle              4.12.0 4.12.0 Symfony SonataBlockBundle
sonata-project/cache                     2.2.0  2.2.0  Cache library
Package sonata-project/cache is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/doctrine-extensions       1.17.0 1.17.0 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 4.2.8  4.2.8  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.11.0 2.11.0 Lightweight Exporter library
sonata-project/form-extensions           1.16.0 1.16.0 Symfony form extensions
sonata-project/twig-extensions           1.10.0 1.10.0 Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
# Put the result here.
symfony/amqp-messenger             v5.4.5  v5.4.5  Symfony AMQP extension Messenger Bridge
symfony/apache-pack                v1.0.1  v1.0.1  A pack for Apache support in Symfony
symfony/asset                      v5.4.7  v6.0.7  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                v5.4.3  v6.0.3  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/cache                      v5.4.8  v6.0.8  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.5.1  v3.0.1  Generic abstractions related to caching
symfony/config                     v5.4.8  v6.0.8  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v5.4.8  v6.0.8  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v5.4.3  v6.0.3  Converts CSS selectors to XPath expressions
symfony/debug-bundle               v5.4.3  v6.0.3  Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge into the Symfony full-stack...
symfony/dependency-injection       v5.4.8  v6.0.8  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v3.0.1  v3.0.1  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.4.8  v6.0.8  Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger         v5.4.8  v6.0.8  Symfony Doctrine Messenger Bridge
symfony/dom-crawler                v5.4.6  v6.0.6  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v5.4.5  v6.0.5  Registers environment variables from a .env file
symfony/error-handler              v5.4.8  v6.0.8  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.4.3  v6.0.3  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v3.0.1  v3.0.1  Generic abstractions related to dispatching event
symfony/expression-language        v5.4.8  v6.0.8  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.4.7  v6.0.7  Provides basic utilities for the filesystem
symfony/finder                     v5.4.8  v6.0.8  Finds files and directories via an intuitive fluent interface
symfony/flex                       v2.1.8  v2.1.8  Composer plugin for Symfony
symfony/form                       v5.4.8  v6.0.8  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v5.4.8  v6.0.8  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v5.4.8  v6.0.8  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.5.1  v3.0.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.4.8  v6.0.8  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.4.8  v6.0.8  Provides a structured process for converting a Request into a Response
symfony/intl                       v5.4.8  v6.0.8  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/lock                       v5.4.7  v6.0.7  Creates and manages locks, a mechanism to provide exclusive access to a shared resource
symfony/maker-bundle               v1.43.0 v1.43.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                  v5.4.8  v6.0.8  Helps applications send and receive messages to/from other applications or via message queues
symfony/monolog-bridge             v5.4.3  v6.0.3  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.8.0  v3.8.0  Symfony MonologBundle
symfony/options-resolver           v5.4.3  v6.0.3  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v5.4.8  v6.0.8  Provides password hashing utilities
symfony/phpunit-bridge             v6.0.8  v6.0.8  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme     v1.25.0 v1.25.0 Symfony polyfill for intl's grapheme_* functions
symfony/process                    v5.4.8  v6.0.8  Executes commands in sub-processes
symfony/property-access            v5.4.8  v6.0.8  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v5.4.7  v6.0.7  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v5.4.6  v6.0.6  Provides integration for ProxyManager with various Symfony components
symfony/redis-messenger            v5.4.6  v6.0.7  Symfony Redis extension Messenger Bridge
symfony/routing                    v5.4.8  v6.0.8  Maps an HTTP request to a set of configuration variables
symfony/runtime                    v5.4.8  v6.0.8  Enables decoupling PHP applications from global state
symfony/security-acl               v3.3.1  v3.3.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v5.4.8  v6.0.8  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v5.4.8  v6.0.8  Symfony Security Component - Core Library
symfony/security-csrf              v5.4.3  v6.0.3  Symfony Security Component - CSRF Library
symfony/security-guard             v5.4.3  v5.4.3  Symfony Security Component - Guard
symfony/security-http              v5.4.8  v6.0.8  Symfony Security Component - HTTP Integration
symfony/serializer                 v5.4.8  v6.0.8  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts          v2.5.1  v3.0.1  Generic abstractions related to writing services
symfony/stopwatch                  v5.4.5  v6.0.5  Provides a way to profile code
symfony/string                     v5.4.8  v6.0.8  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                v5.4.8  v6.0.8  Provides tools to internationalize your application
symfony/translation-contracts      v2.5.1  v3.0.1  Generic abstractions related to translation
symfony/twig-bridge                v5.4.8  v6.0.8  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v5.4.8  v6.0.8  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v5.4.8  v6.0.8  Provides tools to validate values
symfony/var-dumper                 v5.4.8  v6.0.8  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.4.8  v6.0.8  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                   v5.4.3  v6.0.3  Manages links between resources
symfony/web-profiler-bundle        v5.4.8  v6.0.8  Provides a development tool that gives detailed information about the execution of any request
symfony/webapp-meta                v1.0.0  v1.0.0  A meta package for the web app pack
symfony/webpack-encore-bundle      v1.14.1 v1.14.1 Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v5.4.3  v6.0.3  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

```
$ php -v
# Put the result here.
PHP 8.1.6 (cli) (built: May 17 2022 16:48:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.6, Copyright (c), by Zend Technologies
```

## Subject

#7824 broke datepicker functionality.
Current version of the datetimepicker library in sonata-project/form-extensions uses [`.size()`](https://api.jquery.com/size/) function, which is removed in jQuery 3.0 , thus the datepicker in an input group does not work anymore.

## Steps to reproduce
Add a datepicker form type to any admin with the default `'datepicker_use_button' => true` option.
This way a bootstrap input-group is rendered by default with a calendar button.

## Expected results
The datepicker can be opened by clicking on the calendar button.

## Actual results
JS error
```
jQuery.Deferred exception: o.element.find(...).size is not a function TypeError: o.element.find(...).size is not a function
    at u (https://127.0.0.1:8000/bundles/sonataform/app.js:1:816)
    at new s (https://127.0.0.1:8000/bundles/sonataform/app.js:1:22219)
    at HTMLDivElement.<anonymous> (https://127.0.0.1:8000/bundles/sonataform/app.js:1:22349)
    at Function.each (https://127.0.0.1:8000/bundles/sonataadmin/app.js:1:144954)
    at T.fn.init.each (https://127.0.0.1:8000/bundles/sonataadmin/app.js:1:143433)
    at T.fn.init.e.fn.datetimepicker (https://127.0.0.1:8000/bundles/sonataform/app.js:1:22268)
    at HTMLDocument.<anonymous> (https://127.0.0.1:8000/ep/date-range-unique/create:405:51)
    at c (https://127.0.0.1:8000/bundles/sonataadmin/app.js:1:172313)
    at u (https://127.0.0.1:8000/bundles/sonataadmin/app.js:1:172615)
```

### PR DESCRIPTION
**Pull request by franmomu**
## Subject

Fixes https://github.com/sonata-project/SonataAdminBundle/issues/7830

@fracsi if you could give it a try

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Changed
- Fix compatibility of `bootstrap-datetimepicker` with jQuery 3
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
Tomorrow I will take a look, it might not be enough reading: https://github.com/Eonasdan/tempus-dominus/issues/1657

**Comment by jordisala1991** [comment]
I did a test of this with a basic date time picker and a date picker and it works, not sure if there is an advanced behavior that is still wrong but the basic:

```
use Sonata\Form\Type\DatePickerType;
use Sonata\Form\Type\DateTimePickerType;

->add('fake', DateTimePickerType::class, [
    'mapped' => false,
])
->add('fake2', DatePickerType::class, [
    'mapped' => false,
])
```

works fine with this change.

**Comment by jordisala1991** [comment]
Can you fix PHPStan?

**Comment by franmomu** [comment]
I'll see if I can take a look later, but maybe we should deprecate passing an array as argument 1.

**Review by jordisala1991 — APPROVED** [review]
I would say that the changelog should mention compatibility with jQuery 3 instead on what you changed. It is preferred to know what you fixed.

**Review by VincentLanglet — APPROVED** [review]

**Pull request merged**
