### PR TITLE
Update npm packages

### PR DESCRIPTION
**Pull request by haivala**
## Subject

npm pagkages should be updated so I updated them all

I am targeting this branch, because {reason}.

## Changelog

```markdown

### Changed
- Updated and built all npm packages to the newest ones
```

### CODE REVIEW

**Review by VincentLanglet — COMMENTED** [review]
Why does it create new files ?

**Comment by haivala** [comment]
For example: There is new translations to the calendar

**Comment by haivala** [comment]
Actually that is the only reason.

**Review by VincentLanglet — APPROVED** [review]

**Comment by haivala** [comment]
Would be nice to have release after this

**Comment by VincentLanglet** [comment]
> Would be nice to have release after this

Does it provide a new feature or solve a security issue ? If not, that does seems to be a priority

**Comment by haivala** [comment]
It fixes Finnish translations in the calendar.

**Comment by VincentLanglet** [comment]
Done

**Pull request merged**
